export const DEPARTMENT = [
    "Sales",
    "Marketing",
    "Engineering",
    "Human Ressources",
    "Legal"
]

export const STATES = [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District Of Columbia",
    "Federated States Of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virgin Islands",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
]

export const TYPE_NAMES = {
    firstName: 'First Name',
    lastName: 'Last Name',
    birthDate: 'Birth Date',
    startDate: 'Start Date',
    street:'Street',
    city: 'City',
    state: 'State',
    zipCode: 'ZipCode',
    department: 'Department',
}

export const DATA_TYPE = {
    firstName: '',
    lastName: '',
    birthDate: '',
    startDate: '',
    street:'',
    city: '',
    state: '',
    zipCode: '',
    department: '',
}